apiVersion: apps/v1 
kind: Deployment
metadata:
  name: pycon-deployment
spec:
  selector:
    matchLabels:
      app: pyconapp
  replicas: 1
  template:
    metadata:
      labels:
        app: pyconapp
    spec:
      containers:
      - name: pyconcontainer
        image: tarunpothulapati/pyconapp
        ports:
        - containerPort: 5000
